class Try
{
	static public  void main(String[] args)
	{
		int x=20;
		try
		{
//			int x=10;
		}
		catch (Exception e)
		{
//			System.out.println("inside the catch block of the "+x);
		}
		System.out.println("in the outside of the catch block"+x);
	}
}